### ISSUE TITLE
Why you have so many unused fragment?

### ISSUE THREAD

**Issue by namchuai** [Thuonglt2/AnRoi#2]
You have so many unused fragment. E.g. Fragment22,etc. Why do you have so many fragment class? Why don't you reuse it?

**Comment by Thuonglt2** [comment]
Done
Fragment is reused:
        public Fragment getItem(int pos) {
                 QuestionFragment questionFragment = new QuestionFragment();
                 Bundle bundle = new Bundle();
                 bundle.putParcelable("QUESTION", questionList.get(pos));
                 questionFragment.setArguments(bundle);
                  return questionFragment;
         }
