### ISSUE TITLE
Request: Dynamic the number of fragment based on Question

### ISSUE THREAD

**Issue by namchuai** [Thuonglt2/AnRoi#3]
Let's say we have about 40 question => So you need to have a view pager with 40 fragment inside.
Please don't hard code the number of fragment. Let it based on the number of Question object.

**Comment by Thuonglt2** [comment]
Done
- Fragments are reused, a new fragment is created by getItem() call.
- Number of fragments are based on number of Question object:
             public int getCount() {
                    return questionList.size();
             }
